sudo: false

language: node_js

node_js: "7"

cache:
  yarn: true
  directories:
    - node_modules
    - public
    - dist

env:
  # Build options
  - PUBLIC_PATH="/$(basename $TRAVIS_REPO_SLUG)/"
    OFFLINE=true

install:
  - yarn install --pure-lockfile

script:
  - yarn run test
  - yarn run lint
  - yarn run build:prod
  - yarn run build:static

before_deploy:
  # Copy README to public folder
  - cp ./README.md ./public/README.md

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
